spring:
  config:
    activate:
      on-profile: staging

  jpa:
    show-sql: false

  kafka:
    listener:
      auto-startup: true

  task:
    scheduling:
      enabled: true

logging:
  level:
    root: INFO
    com.internetcafe: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
    org.springframework.mail: INFO
    org.hibernate.sql: WARN

management:
  endpoint:
    health:
      show-details: when_authorized

app:
  mail:
    enabled: true
  outbox:
    relay-enabled: true
  storage:
    enabled: false